{% set name = "p-tqdm" %}
{% set version = "1.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/p_tqdm-{{ version }}.tar.gz
  sha256: 877f33e2418b612ad498c6c14872faa68a049d4b1f146d42ca8ada24fc0b79ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pathos
    - python >=3.6
    - six
    - tqdm

test:
  imports:
    - p_tqdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/swansonk14/p_tqdm
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Parallel processing with progress bars
  description: |
    p_tqdm makes parallel processing with progress bars easy. 
    p_tqdm is a wrapper around pathos.multiprocessing and tqdm. Unlike
    Python's default multiprocessing library, pathos provides a more
    flexible parallel map which can apply almost any type of function
    --- including lambda functions, nested functions, and class methods
    --- and can easily handle functions with multiple arguments. tqdm is
    applied on top of pathos's parallel map and displays a progress bar 
    including an estimated time to completion.
  doc_url: https://github.com/swansonk14/p_tqdm
  dev_url: https://github.com/swansonk14/p_tqdm

extra:
  recipe-maintainers:
    - jan-janssen
